import asyncio, json, sys, re
from playwright.async_api import async_playwright

GENERIC_TITLES = re.compile(r"^(lovable|vite|react app|vite \+ react|my app|untitled|index|"
                            r"lovable-generated-project|vite_react_shadcn_ts|generated by lovable|"
                            r"welcome|app|home)\b", re.I)

async def check(browser, host):
    r = {"host": host, "reachable": False, "checks": {}, "err": None}
    ctx = None
    try:
        ctx = await browser.new_context(viewport={"width":390,"height":844},
              user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Safari/604.1",
              ignore_https_errors=True)
        page = await ctx.new_page()
        errs, bad = [], []
        page.on("console", lambda m: errs.append(m.text[:200]) if m.type=="error" else None)
        page.on("pageerror", lambda e: errs.append("PAGEERROR "+str(e)[:200]))
        page.on("response", lambda resp: bad.append(f"{resp.status} {resp.url[:90]}") if resp.status>=400 else None)
        await page.goto(f"https://{host}/", wait_until="networkidle", timeout=35000)
        await page.wait_for_timeout(1500)
        r["reachable"] = True

        m = await page.evaluate("""() => {
            const d=document;
            const q=s=>d.querySelector(s);
            const txt=(d.body?d.body.innerText:'').trim();
            return {
              title: (d.title||'').trim(),
              desc: !!(q('meta[name="description"]') && q('meta[name="description"]').content.trim()),
              og: !!(q('meta[property="og:image"]') && q('meta[property="og:image"]').content.trim()),
              favicon: !!q('link[rel~="icon"]'),
              lang: (d.documentElement.getAttribute('lang')||'').trim(),
              textLen: txt.length,
              scrollW: d.documentElement.scrollWidth,
              clientW: d.documentElement.clientWidth,
              imgsBroken: Array.from(d.images).filter(i=>i.complete && i.naturalWidth===0).length,
              h1: d.querySelectorAll('h1').length
            };
        }""")
        c = r["checks"]
        c["console_errors"]       = len(errs)
        c["failed_requests"]      = len(bad)
        c["mobile_overflow_px"]   = max(0, m["scrollW"] - m["clientW"])
        c["title"]                = m["title"]
        c["title_generic_or_missing"] = (not m["title"]) or bool(GENERIC_TITLES.match(m["title"]))
        c["no_meta_description"]  = not m["desc"]
        c["no_og_image"]          = not m["og"]
        c["no_favicon"]           = not m["favicon"]
        c["no_lang"]              = not m["lang"]
        c["blank_page"]           = m["textLen"] < 60
        c["broken_images"]        = m["imgsBroken"]
        c["no_h1"]                = m["h1"] == 0
        r["sample_errors"] = errs[:3]
        r["sample_failed"] = bad[:3]
    except Exception as e:
        r["err"] = f"{type(e).__name__}: {str(e)[:120]}"
    finally:
        if ctx:
            try: await ctx.close()
            except: pass
    return r

def score(c):
    """100 = listo para que lo use gente. Cada falla resta."""
    s = 100
    if c.get("blank_page"): s -= 40
    s -= min(20, c.get("console_errors",0)*5)
    s -= min(15, c.get("failed_requests",0)*5)
    if c.get("mobile_overflow_px",0) > 8: s -= 15
    if c.get("title_generic_or_missing"): s -= 12
    if c.get("no_meta_description"): s -= 8
    if c.get("no_og_image"): s -= 8
    if c.get("no_favicon"): s -= 4
    if c.get("no_lang"): s -= 3
    s -= min(10, c.get("broken_images",0)*5)
    if c.get("no_h1"): s -= 3
    return max(0, s)

async def main():
    hosts=[h.strip() for h in open(sys.argv[1]) if h.strip()]
    out=[]
    async with async_playwright() as p:
        browser = await p.chromium.launch(args=["--no-sandbox"], proxy={"server":"http://127.0.0.1:36247"})
        sem = asyncio.Semaphore(6)
        async def run(h):
            async with sem:
                return await check(browser, h)
        for i in range(0, len(hosts), 6):
            batch = await asyncio.gather(*[run(h) for h in hosts[i:i+6]])
            out.extend(batch)
            print(f"{len(out)}/{len(hosts)}", flush=True)
        await browser.close()
    for r in out:
        r["score"] = score(r["checks"]) if r["reachable"] else None
    json.dump(out, open(sys.argv[2],"w"), indent=1)
    print("listo")
asyncio.run(main())
